{% set name = "intersphinx-registry" %}
{% set version = "0.2411.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intersphinx_registry-{{ version }}.tar.gz
  sha256: 722601c22cb64281c1e32394b3aef074e6a0c9c23c86a0ec952ce20e8f1be9e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8

test:
  imports:
    - intersphinx_registry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Carreau/intersphinx_registry
  summary: This package provides convenient utilities and data to write a sphinx config file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - Carreau
