{% set name = "intersphinx-registry" %}
{% set version = "0.2411.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intersphinx_registry-{{ version }}.tar.gz
  sha256: c585a6c8038fef01a6d0df4d0efbe25bc8048276bd62608e30c5870e370aca86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8

test:
  imports:
    - intersphinx_registry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Carreau/intersphinx_registry
  summary: This package provides convenient utilities and data to write a sphinx config file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - Carreau
